exports.createError = async(req, res, next) =>{
    try{
        //Strore the error in database

    }catch(error){
        
    }
}